{{- if .Values.apps.mysqlEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      name: {{ .Values.mysql.name }}
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: {{ .Values.mysql.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.mysql.name }}
                  key: {{ .Values.secrets.mysql.key }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          volumeMounts:
            - name: {{ .Values.mysql.volume.storageName }}
              mountPath: {{ .Values.mysql.volume.mountPath }}
      volumes:
        - name: {{ .Values.mysql.volume.storageName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.name }}
{{ end }}
