apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlService.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysqlService.port }}
      targetPort: {{ .Values.mysql.port }}
  type: {{ .Values.mysqlService.type }}
  