{{- if .Values.apps.webEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webDeployment.name }}
  labels:
    app: {{ .Values.webDeployment.name }}
spec:
  replicas: {{ .Values.webDeployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webDeployment.name }}
  template:
    metadata:
      name: {{ .Values.webDeployment.name }}
      labels:
        app: {{ .Values.webDeployment.name }}
    spec:
      containers:
        - name: {{ .Values.webDeployment.name }}
          image: {{ .Values.webDeployment.image }}
          imagePullPolicy: {{ .Values.webDeployment.imagePullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: {{ .Values.webDeployment.port }}
              protocol: TCP
      imagePullSecrets: {{ toYaml .Values.images.pullSecrets | nindent 8 }}
      restartPolicy: {{ .Values.webDeployment.restartPolicy }}
{{ end }}
